version: "3"

volumes:
  vendor:
    driver: local
services:
  php:
    build:
      context: ./images/php
    volumes:
      - ".:/var/www/html:cached"
      - "vendor:/var/www/html/vendor"
    ports:
      - 12380:80
